version: "3"
services:
  springrectivemongoapi:
    #network_mode: "host"
    image: "api:latest"
    environment:
      SERVER_PORT: 8085
      SPRING_APPLICATION_NAME: spring-rective-mongoapi
      SPRING_URI: localhost:27017,mongodb://localhost:27017
      SPRING_DATABASE: dbtest # base mongo
      SPRING_REPOSITORY_ENABLE: 'true'